# -*- coding: utf-8 -*-
"""OLSRegression_DropNa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QF3ekXf-D0Gtk0SBDUTJY2Fu5vfsp-3I
"""

import pandas as pd
df = pd.read_excel("/content/USE_THIS_for_Regression_New.xlsx")
df.head()

df_copy = df.copy()

dffinal=df_copy.dropna(subset=['Ln Income', 'Ln Housing Value'])

dffinal.to_excel('dropNa_USE_THIS.xlsx')